CREATE TABLE "PANTRYDB"."RECIPE" (
	"TITLE_ID" VARCHAR2(400)
	,"TITLE" VARCHAR2(4000)
	,"CREATED_DATE" VARCHAR2(4000)
	,"CATEGORIES" VARCHAR2(4000)
	,"CALORIES" VARCHAR2(4000)
	,"DESCRIPTION" VARCHAR2(4000)
	,"PROTEIN" VARCHAR2(4000)
	,"RATING" VARCHAR2(4000)
	,"SODIUM" VARCHAR2(4000)
	,"SYSTEM_CREATED_AT" DATE DEFAULT sysdate
	,PRIMARY KEY ("TITLE_ID")
	);

CREATE TABLE "PANTRYDB"."RECIPE_DIRECTIONS" (
	"TITLE_ID" VARCHAR2(400)
	,"SEQ" VARCHAR2(400)
	,"NAME" VARCHAR2(4000)
	,"CREATED_AT" DATE DEFAULT sysdate
	,CONSTRAINT "STEP_PK" PRIMARY KEY (
		"TITLE_ID"
		,"SEQ"
		)
	,CONSTRAINT STEP_FK FOREIGN KEY (TITLE_ID) REFERENCES PANTRYDB.RECIPE (TITLE_ID)
	);

CREATE TABLE "PANTRYDB"."RECIPE_INGREDIENTS" (
	"TITLE_ID" VARCHAR2(400)
	,"INGREDIENT_ID" VARCHAR2(400)
	,"INGREDIENT_NAME" VARCHAR2(4000)
	,"CREATED_AT" DATE DEFAULT sysdate
	,CONSTRAINT "ING_PK" PRIMARY KEY (
		"TITLE_ID"
		,"INGREDIENT_ID"
		)
	,CONSTRAINT ing_FK FOREIGN KEY (TITLE_ID) REFERENCES PANTRYDB.RECIPE (TITLE_ID)
	);

CREATE TABLE "PANTRYDB"."RECIPE_STATS" (
	"TITLE" VARCHAR2(400)
	,"RATING" NUMBER
	,"CALORIES" NUMBER
	,"PROTEIN" NUMBER
	,"FAT" NUMBER
	,"SODIUM" NUMBER
	,"CAKEWEEK" NUMBER
	,"WASTELESS" NUMBER
	,"MINUTE22_MEALS" NUMBER
	,"INGREDIENT3_RECIPES" NUMBER
	,"DAYS30_OF_GROCERIES" NUMBER
	,"ADVANCE_PREP_REQUIRED" NUMBER
	,"ALABAMA" NUMBER
	,"ALASKA" NUMBER
	,"ALCOHOLIC" NUMBER
	,"ALMOND" NUMBER
	,"AMARETTO" NUMBER
	,"ANCHOVY" NUMBER
	,"ANISE" NUMBER
	,"ANNIVERSARY" NUMBER
	,"ANTHONY_BOURDAIN" NUMBER
	,"APERITIF" NUMBER
	,"APPETIZER" NUMBER
	,"APPLE" NUMBER
	,"APPLE_JUICE" NUMBER
	,"APRICOT" NUMBER
	,"ARIZONA" NUMBER
	,"ARTICHOKE" NUMBER
	,"ARUGULA" NUMBER
	,"ASIAN_PEAR" NUMBER
	,"ASPARAGUS" NUMBER
	,"ASPEN" NUMBER
	,"ATLANTA" NUMBER
	,"AUSTRALIA" NUMBER
	,"AVOCADO" NUMBER
	,"BACK_TO_SCHOOL" NUMBER
	,"BACKYARD_BBQ" NUMBER
	,"BACON" NUMBER
	,"BAKE" NUMBER
	,"BANANA" NUMBER
	,"BARLEY" NUMBER
	,"BASIL" NUMBER
	,"BASS" NUMBER
	,"BASTILLE_DAY" NUMBER
	,"BEAN" NUMBER
	,"BEEF" NUMBER
	,"BEEF_RIB" NUMBER
	,"BEEF_SHANK" NUMBER
	,"BEEF_TENDERLOIN" NUMBER
	,"BEER" NUMBER
	,"BEET" NUMBER
	,"BELL_PEPPER" NUMBER
	,"BERRY" NUMBER
	,"BEVERLY_HILLS" NUMBER
	,"BIRTHDAY" NUMBER
	,"BISCUIT" NUMBER
	,"BITTERS" NUMBER
	,"BLACKBERRY" NUMBER
	,"BLENDER" NUMBER
	,"BLUE_CHEESE" NUMBER
	,"BLUEBERRY" NUMBER
	,"BOIL" NUMBER
	,"BOK_CHOY" NUMBER
	,"BON_APPÉTIT" NUMBER
	,"BON_APP��TIT" NUMBER
	,"BOSTON" NUMBER
	,"BOURBON" NUMBER
	,"BRAISE" NUMBER
	,"BRAN" NUMBER
	,"BRANDY" NUMBER
	,"BREAD" NUMBER
	,"BREADCRUMBS" NUMBER
	,"BREAKFAST" NUMBER
	,"BRIE" NUMBER
	,"BRINE" NUMBER
	,"BRISKET" NUMBER
	,"BROCCOLI" NUMBER
	,"BROCCOLI_RABE" NUMBER
	,"BROIL" NUMBER
	,"BROOKLYN" NUMBER
	,"BROWN_RICE" NUMBER
	,"BROWNIE" NUMBER
	,"BRUNCH" NUMBER
	,"BRUSSEL_SPROUT" NUMBER
	,"BUFFALO" NUMBER
	,"BUFFET" NUMBER
	,"BULGARIA" NUMBER
	,"BULGUR" NUMBER
	,"BURRITO" NUMBER
	,"BUTTER" NUMBER
	,"BUTTERMILK" NUMBER
	,"BUTTERNUT_SQUASH" NUMBER
	,"BUTTERSCOTCH_CARAMEL" NUMBER
	,"CABBAGE" NUMBER
	,"CAKE" NUMBER
	,"CALIFORNIA" NUMBER
	,"CALVADOS" NUMBER
	,"CAMBRIDGE" NUMBER
	,"CAMPARI" NUMBER
	,"CAMPING" NUMBER
	,"CANADA" NUMBER
	,"CANDY" NUMBER
	,"CANDY_THERMOMETER" NUMBER
	,"CANTALOUPE" NUMBER
	,"CAPERS" NUMBER
	,"CARAWAY" NUMBER
	,"CARDAMOM" NUMBER
	,"CARROT" NUMBER
	,"CASHEW" NUMBER
	,"CASSEROLE_GRATIN" NUMBER
	,"CAULIFLOWER" NUMBER
	,"CAVIAR" NUMBER
	,"CELERY" NUMBER
	,"CHAMBORD" NUMBER
	,"CHAMPAGNE" NUMBER
	,"CHARD" NUMBER
	,"CHARTREUSE" NUMBER
	,"CHEDDAR" NUMBER
	,"CHEESE" NUMBER
	,"CHERRY" NUMBER
	,"CHESTNUT" NUMBER
	,"CHICAGO" NUMBER
	,"CHICKEN" NUMBER
	,"CHICKPEA" NUMBER
	,"CHILE" NUMBER
	,"CHILE_PEPPER" NUMBER
	,"CHILI" NUMBER
	,"CHILL" NUMBER
	,"CHIVE" NUMBER
	,"CHOCOLATE" NUMBER
	,"CHRISTMAS" NUMBER
	,"CHRISTMAS_EVE" NUMBER
	,"CILANTRO" NUMBER
	,"CINCO_DE_MAYO" NUMBER
	,"CINNAMON" NUMBER
	,"CITRUS" NUMBER
	,"CLAM" NUMBER
	,"CLOVE" NUMBER
	,"COBBLER_CRUMBLE" NUMBER
	,"COCKTAIL" NUMBER
	,"COCKTAIL_PARTY" NUMBER
	,"COCONUT" NUMBER
	,"COD" NUMBER
	,"COFFEE" NUMBER
	,"COFFEE_GRINDER" NUMBER
	,"COGNAC_ARMAGNAC" NUMBER
	,"COLLARD_GREENS" NUMBER
	,"COLORADO" NUMBER
	,"COLUMBUS" NUMBER
	,"CONDIMENT" NUMBER
	,"CONDIMENT_SPREAD" NUMBER
	,"CONNECTICUT" NUMBER
	,"COOK_LIKE_A_DINER" NUMBER
	,"COOKBOOK_CRITIC" NUMBER
	,"COOKIE" NUMBER
	,"COOKIES" NUMBER
	,"CORIANDER" NUMBER
	,"CORN" NUMBER
	,"CORNMEAL" NUMBER
	,"COSTA_MESA" NUMBER
	,"COTTAGE_CHEESE" NUMBER
	,"COUSCOUS" NUMBER
	,"CRAB" NUMBER
	,"CRANBERRY" NUMBER
	,"CRANBERRY_SAUCE" NUMBER
	,"CREAM_CHEESE" NUMBER
	,"CRÉME_DE_CACAO" NUMBER
	,"CRÊPE" NUMBER
	,"CR��ME_DE_CACAO" NUMBER
	,"CUBA" NUMBER
	,"CUCUMBER" NUMBER
	,"CUMIN" NUMBER
	,"CUPCAKE" NUMBER
	,"CURRANT" NUMBER
	,"CURRY" NUMBER
	,"CUSTARD" NUMBER
	,"DAIRY" NUMBER
	,"DAIRY_FREE" NUMBER
	,"DALLAS" NUMBER
	,"DATES" NUMBER
	,"DEEPFRY" NUMBER
	,"DENVER" NUMBER
	,"DESSERT" NUMBER
	,"DIGESTIF" NUMBER
	,"DILL" NUMBER
	,"DINNER" NUMBER
	,"DIP" NUMBER
	,"DIWALI" NUMBER
	,"DOMINICAN_REPUBLIC" NUMBER
	,"DORIE_GREENSPAN" NUMBER
	,"DOUBLE_BOILER" NUMBER
	,"DRIED_FRUIT" NUMBER
	,"DRINK" NUMBER
	,"DRINKS" NUMBER
	,"DUCK" NUMBER
	,"EASTER" NUMBER
	,"EAU_DE_VIE" NUMBER
	,"EDIBLE_GIFT" NUMBER
	,"EGG" NUMBER
	,"EGG_NOG" NUMBER
	,"EGGPLANT" NUMBER
	,"EGYPT" NUMBER
	,"EMERIL_LAGASSE" NUMBER
	,"ENDIVE" NUMBER
	,"ENGAGEMENT_PARTY" NUMBER
	,"ENGLAND" NUMBER
	,"ENTERTAINING" NUMBER
	,"EPI__USHG" NUMBER
	,"EPI_LOVES_THE_MICROWAVE" NUMBER
	,"ESCAROLE" NUMBER
	,"FALL" NUMBER
	,"FAMILY_REUNION" NUMBER
	,"FAT_FREE" NUMBER
	,"FATHERS_DAY" NUMBER
	,"FENNEL" NUMBER
	,"FETA" NUMBER
	,"FIG" NUMBER
	,"FISH" NUMBER
	,"FLAMING_HOT_SUMMER" NUMBER
	,"FLAT_BREAD" NUMBER
	,"FLORIDA" NUMBER
	,"FONTINA" NUMBER
	,"FOOD_PROCESSOR" NUMBER
	,"FORTIFIED_WINE" NUMBER
	,"FOURTH_OF_JULY" NUMBER
	,"FRANCE" NUMBER
	,"FRANGELICO" NUMBER
	,"FRANKENRECIPE" NUMBER
	,"FREEZE_CHILL" NUMBER
	,"FREEZER_FOOD" NUMBER
	,"FRIENDSGIVING" NUMBER
	,"FRITTATA" NUMBER
	,"FRITTER" NUMBER
	,"FROZEN_DESSERT" NUMBER
	,"FRUIT" NUMBER
	,"FRUIT_JUICE" NUMBER
	,"FRY" NUMBER
	,"GAME" NUMBER
	,"GARLIC" NUMBER
	,"GEORGIA" NUMBER
	,"GERMANY" NUMBER
	,"GIN" NUMBER
	,"GINGER" NUMBER
	,"GOAT_CHEESE" NUMBER
	,"GOOSE" NUMBER
	,"GOUDA" NUMBER
	,"GOURMET" NUMBER
	,"GRADUATION" NUMBER
	,"GRAINS" NUMBER
	,"GRAND_MARNIER" NUMBER
	,"GRANOLA" NUMBER
	,"GRAPE" NUMBER
	,"GRAPEFRUIT" NUMBER
	,"GRAPPA" NUMBER
	,"GREEN_BEAN" NUMBER
	,"GREEN_ONION_SCALLION" NUMBER
	,"GRILL" NUMBER
	,"GRILL_BARBECUE" NUMBER
	,"GROUND_BEEF" NUMBER
	,"GROUND_LAMB" NUMBER
	,"GUAM" NUMBER
	,"GUAVA" NUMBER
	,"HAITI" NUMBER
	,"HALIBUT" NUMBER
	,"HALLOWEEN" NUMBER
	,"HAM" NUMBER
	,"HAMBURGER" NUMBER
	,"HANUKKAH" NUMBER
	,"HARPERCOLLINS" NUMBER
	,"HAWAII" NUMBER
	,"HAZELNUT" NUMBER
	,"HEALDSBURG" NUMBER
	,"HEALTHY" NUMBER
	,"HERB" NUMBER
	,"HIGH_FIBER" NUMBER
	,"HOLLYWOOD" NUMBER
	,"HOMINY_CORNMEAL_MASA" NUMBER
	,"HONEY" NUMBER
	,"HONEYDEW" NUMBER
	,"HORS_DOEUVRE" NUMBER
	,"HORSERADISH" NUMBER
	,"HOT_DRINK" NUMBER
	,"HOT_PEPPER" NUMBER
	,"HOUSE__GARDEN" NUMBER
	,"HOUSE_COCKTAIL" NUMBER
	,"HOUSTON" NUMBER
	,"HUMMUS" NUMBER
	,"ICE_CREAM" NUMBER
	,"ICE_CREAM_MACHINE" NUMBER
	,"ICED_COFFEE" NUMBER
	,"ICED_TEA" NUMBER
	,"IDAHO" NUMBER
	,"ILLINOIS" NUMBER
	,"INDIANA" NUMBER
	,"IOWA" NUMBER
	,"IRELAND" NUMBER
	,"ISRAEL" NUMBER
	,"ITALY" NUMBER
	,"JALAPEÑO" NUMBER
	,"JAM_OR_JELLY" NUMBER
	,"JAMAICA" NUMBER
	,"JAPAN" NUMBER
	,"JERUSALEM_ARTICHOKE" NUMBER
	,"JUICER" NUMBER
	,"JÍCAMA" NUMBER
	,"KAHLÚA" NUMBER
	,"KALE" NUMBER
	,"KANSAS" NUMBER
	,"KANSAS_CITY" NUMBER
	,"KENTUCKY" NUMBER
	,"KENTUCKY_DERBY" NUMBER
	,"KIDFRIENDLY" NUMBER
	,"KIDNEY_FRIENDLY" NUMBER
	,"KIRSCH" NUMBER
	,"KITCHEN_OLYMPICS" NUMBER
	,"KIWI" NUMBER
	,"KOSHER" NUMBER
	,"KOSHER_FOR_PASSOVER" NUMBER
	,"KUMQUAT" NUMBER
	,"KWANZAA" NUMBER
	,"LABOR_DAY" NUMBER
	,"LAMB" NUMBER
	,"LAMB_CHOP" NUMBER
	,"LAMB_SHANK" NUMBER
	,"LANCASTER" NUMBER
	,"LAS_VEGAS" NUMBER
	,"LASAGNA" NUMBER
	,"LEAFY_GREEN" NUMBER
	,"LEEK" NUMBER
	,"LEGUME" NUMBER
	,"LEMON" NUMBER
	,"LEMON_JUICE" NUMBER
	,"LEMONGRASS" NUMBER
	,"LENTIL" NUMBER
	,"LETTUCE" NUMBER
	,"LIMA_BEAN" NUMBER
	,"LIME" NUMBER
	,"LIME_JUICE" NUMBER
	,"LINGONBERRY" NUMBER
	,"LIQUEUR" NUMBER
	,"LOBSTER" NUMBER
	,"LONDON" NUMBER
	,"LONG_BEACH" NUMBER
	,"LOS_ANGELES" NUMBER
	,"LOUISIANA" NUMBER
	,"LOUISVILLE" NUMBER
	,"LOW_CAL" NUMBER
	,"LOW_CARB" NUMBER
	,"LOW_CHOLESTEROL" NUMBER
	,"LOW_FAT" NUMBER
	,"LOW_SODIUM" NUMBER
	,"LOW_SUGAR" NUMBER
	,"LOW_NO_SUGAR" NUMBER
	,"LUNAR_NEW_YEAR" NUMBER
	,"LUNCH" NUMBER
	,"LYCHEE" NUMBER
	,"MACADAMIA_NUT" NUMBER
	,"MACARONI_AND_CHEESE" NUMBER
	,"MAINE" NUMBER
	,"MANDOLINE" NUMBER
	,"MANGO" NUMBER
	,"MAPLE_SYRUP" NUMBER
	,"MARDI_GRAS" NUMBER
	,"MARGARITA" NUMBER
	,"MARINADE" NUMBER
	,"MARINATE" NUMBER
	,"MARSALA" NUMBER
	,"MARSCARPONE" NUMBER
	,"MARSHMALLOW" NUMBER
	,"MARTINI" NUMBER
	,"MARYLAND" NUMBER
	,"MASSACHUSETTS" NUMBER
	,"MAYONNAISE" NUMBER
	,"MEAT" NUMBER
	,"MEATBALL" NUMBER
	,"MEATLOAF" NUMBER
	,"MELON" NUMBER
	,"MEXICO" NUMBER
	,"MEZCAL" NUMBER
	,"MIAMI" NUMBER
	,"MICHIGAN" NUMBER
	,"MICROWAVE" NUMBER
	,"MIDORI" NUMBER
	,"MILK_CREAM" NUMBER
	,"MINNEAPOLIS" NUMBER
	,"MINNESOTA" NUMBER
	,"MINT" NUMBER
	,"MISSISSIPPI" NUMBER
	,"MISSOURI" NUMBER
	,"MIXER" NUMBER
	,"MOLASSES" NUMBER
	,"MONTEREY_JACK" NUMBER
	,"MORTAR_AND_PESTLE" NUMBER
	,"MOTHERS_DAY" NUMBER
	,"MOZZARELLA" NUMBER
	,"MUFFIN" NUMBER
	,"MUSHROOM" NUMBER
	,"MUSSEL" NUMBER
	,"MUSTARD" NUMBER
	,"MUSTARD_GREENS" NUMBER
	,"NANCY_SILVERTON" NUMBER
	,"NEBRASKA" NUMBER
	,"NECTARINE" NUMBER
	,"NEW_HAMPSHIRE" NUMBER
	,"NEW_JERSEY" NUMBER
	,"NEW_MEXICO" NUMBER
	,"NEW_ORLEANS" NUMBER
	,"NEW_YEARS_DAY" NUMBER
	,"NEW_YEARS_EVE" NUMBER
	,"NEW_YORK" NUMBER
	,"NO_MEAT_NO_PROBLEM" NUMBER
	,"NO_SUGAR_ADDED" NUMBER
	,"NOCOOK" NUMBER
	,"NONALCOHOLIC" NUMBER
	,"NOODLE" NUMBER
	,"NORTH_CAROLINA" NUMBER
	,"NUT" NUMBER
	,"NUTMEG" NUMBER
	,"OAT" NUMBER
	,"OATMEAL" NUMBER
	,"OCTOPUS" NUMBER
	,"OHIO" NUMBER
	,"OKLAHOMA" NUMBER
	,"OKRA" NUMBER
	,"OKTOBERFEST" NUMBER
	,"OLIVE" NUMBER
	,"OMELET" NUMBER
	,"ONEPOT_MEAL" NUMBER
	,"ONION" NUMBER
	,"ORANGE" NUMBER
	,"ORANGE_JUICE" NUMBER
	,"OREGANO" NUMBER
	,"OREGON" NUMBER
	,"ORGANIC" NUMBER
	,"ORZO" NUMBER
	,"OSCARS" NUMBER
	,"OYSTER" NUMBER
	,"PACIFIC_PALISADES" NUMBER
	,"PALEO" NUMBER
	,"PANFRY" NUMBER
	,"PANCAKE" NUMBER
	,"PAPAYA" NUMBER
	,"PAPRIKA" NUMBER
	,"PARADE" NUMBER
	,"PARIS" NUMBER
	,"PARMESAN" NUMBER
	,"PARSLEY" NUMBER
	,"PARSNIP" NUMBER
	,"PARTY" NUMBER
	,"PASADENA" NUMBER
	,"PASSION_FRUIT" NUMBER
	,"PASSOVER" NUMBER
	,"PASTA" NUMBER
	,"PASTA_MAKER" NUMBER
	,"PASTRY" NUMBER
	,"PEA" NUMBER
	,"PEACH" NUMBER
	,"PEANUT" NUMBER
	,"PEANUT_BUTTER" NUMBER
	,"PEANUT_FREE" NUMBER
	,"PEAR" NUMBER
	,"PECAN" NUMBER
	,"PENNSYLVANIA" NUMBER
	,"PEPPER" NUMBER
	,"PERNOD" NUMBER
	,"PERSIAN_NEW_YEAR" NUMBER
	,"PERSIMMON" NUMBER
	,"PERU" NUMBER
	,"PESCATARIAN" NUMBER
	,"PHILIPPINES" NUMBER
	,"PHYLLO_PUFF_PASTRY_DOUGH" NUMBER
	,"PICKLES" NUMBER
	,"PICNIC" NUMBER
	,"PIE" NUMBER
	,"PINE_NUT" NUMBER
	,"PINEAPPLE" NUMBER
	,"PISTACHIO" NUMBER
	,"PITTSBURGH" NUMBER
	,"PIZZA" NUMBER
	,"PLANTAIN" NUMBER
	,"PLUM" NUMBER
	,"POACH" NUMBER
	,"POBLANO" NUMBER
	,"POKER_GAME_NIGHT" NUMBER
	,"POMEGRANATE" NUMBER
	,"POMEGRANATE_JUICE" NUMBER
	,"POPPY" NUMBER
	,"PORK" NUMBER
	,"PORK_CHOP" NUMBER
	,"PORK_RIB" NUMBER
	,"PORK_TENDERLOIN" NUMBER
	,"PORT" NUMBER
	,"PORTLAND" NUMBER
	,"POT_PIE" NUMBER
	,"POTATO" NUMBER
	,"POTATO_SALAD" NUMBER
	,"POTLUCK" NUMBER
	,"POULTRY" NUMBER
	,"POULTRY_SAUSAGE" NUMBER
	,"PRESSURE_COOKER" NUMBER
	,"PROSCIUTTO" NUMBER
	,"PROVIDENCE" NUMBER
	,"PRUNE" NUMBER
	,"PUMPKIN" NUMBER
	,"PUNCH" NUMBER
	,"PURIM" NUMBER
	,"QUAIL" NUMBER
	,"QUICHE" NUMBER
	,"QUICK__EASY" NUMBER
	,"QUICK_AND_HEALTHY" NUMBER
	,"QUINCE" NUMBER
	,"QUINOA" NUMBER
	,"RABBIT" NUMBER
	,"RACK_OF_LAMB" NUMBER
	,"RADICCHIO" NUMBER
	,"RADISH" NUMBER
	,"RAISIN" NUMBER
	,"RAMADAN" NUMBER
	,"RAMEKIN" NUMBER
	,"RASPBERRY" NUMBER
	,"RAW_" NUMBER
	,"RED_WINE" NUMBER
	,"RHODE_ISLAND" NUMBER
	,"RHUBARB" NUMBER
	,"RICE" NUMBER
	,"RICOTTA" NUMBER
	,"ROAST" NUMBER
	,"ROOT_VEGETABLE" NUMBER
	,"ROSEMARY" NUMBER
	,"ROSH_HASHANAH_YOM_KIPPUR" NUMBER
	,"ROSÉ" NUMBER
	,"RUB" NUMBER
	,"RUM" NUMBER
	,"RUTABAGA" NUMBER
	,"RYE" NUMBER
	,"SAFFRON" NUMBER
	,"SAGE" NUMBER
	,"SAKE" NUMBER
	,"SALAD" NUMBER
	,"SALAD_DRESSING" NUMBER
	,"SALMON" NUMBER
	,"SALSA" NUMBER
	,"SAN_FRANCISCO" NUMBER
	,"SANDWICH" NUMBER
	,"SANDWICH_THEORY" NUMBER
	,"SANGRIA" NUMBER
	,"SANTA_MONICA" NUMBER
	,"SARDINE" NUMBER
	,"SAUCE" NUMBER
	,"SAUSAGE" NUMBER
	,"SAUTÉ" NUMBER
	,"SCALLOP" NUMBER
	,"SCOTCH" NUMBER
	,"SEAFOOD" NUMBER
	,"SEATTLE" NUMBER
	,"SEED" NUMBER
	,"SELF_" NUMBER
	,"SEMOLINA" NUMBER
	,"SESAME" NUMBER
	,"SESAME_OIL" NUMBER
	,"SHALLOT" NUMBER
	,"SHAVUOT" NUMBER
	,"SHELLFISH" NUMBER
	,"SHERRY" NUMBER
	,"SHOWER" NUMBER
	,"SHRIMP" NUMBER
	,"SIDE" NUMBER
	,"SIMMER" NUMBER
	,"SKEWER" NUMBER
	,"SLOW_COOKER" NUMBER
	,"SMOKER" NUMBER
	,"SMOOTHIE" NUMBER
	,"SNAPPER" NUMBER
	,"SORBET" NUMBER
	,"SOUFFL_MERINGUE" NUMBER
	,"SOUP_STEW" NUMBER
	,"SOUR_CREAM" NUMBER
	,"SOURDOUGH" NUMBER
	,"SOUTH_CAROLINA" NUMBER
	,"SOY" NUMBER
	,"SOY_FREE" NUMBER
	,"SOY_SAUCE" NUMBER
	,"SPAIN" NUMBER
	,"SPARKLING_WINE" NUMBER
	,"SPICE" NUMBER
	,"SPINACH" NUMBER
	,"SPIRIT" NUMBER
	,"SPRING" NUMBER
	,"SPRITZER" NUMBER
	,"SQUASH" NUMBER
	,"SQUID" NUMBER
	,"ST_LOUIS" NUMBER
	,"ST_PATRICKS_DAY" NUMBER
	,"STEAK" NUMBER
	,"STEAM" NUMBER
	,"STEW" NUMBER
	,"STIRFRY" NUMBER
	,"STOCK" NUMBER
	,"STRAWBERRY" NUMBER
	,"STUFFING_DRESSING" NUMBER
	,"SUGAR_CONSCIOUS" NUMBER
	,"SUGAR_SNAP_PEA" NUMBER
	,"SUKKOT" NUMBER
	,"SUMMER" NUMBER
	,"SUPER_BOWL" NUMBER
	,"SUZANNE_GOIN" NUMBER
	,"SWEET_POTATO_YAM" NUMBER
	,"SWISS_CHEESE" NUMBER
	,"SWITZERLAND" NUMBER
	,"SWORDFISH" NUMBER
	,"TACO" NUMBER
	,"TAILGATING" NUMBER
	,"TAMARIND" NUMBER
	,"TANGERINE" NUMBER
	,"TAPIOCA" NUMBER
	,"TARRAGON" NUMBER
	,"TART" NUMBER
	,"TEA" NUMBER
	,"TENNESSEE" NUMBER
	,"TEQUILA" NUMBER
	,"TESTED__IMPROVED" NUMBER
	,"TEXAS" NUMBER
	,"THANKSGIVING" NUMBER
	,"THYME" NUMBER
	,"TILAPIA" NUMBER
	,"TOFU" NUMBER
	,"TOMATILLO" NUMBER
	,"TOMATO" NUMBER
	,"TORTILLAS" NUMBER
	,"TREE_NUT" NUMBER
	,"TREE_NUT_FREE" NUMBER
	,"TRIPLE_SEC" NUMBER
	,"TROPICAL_FRUIT" NUMBER
	,"TROUT" NUMBER
	,"TUNA" NUMBER
	,"TURNIP" NUMBER
	,"UTAH" NUMBER
	,"VALENTINES_DAY" NUMBER
	,"VANILLA" NUMBER
	,"VEAL" NUMBER
	,"VEGAN" NUMBER
	,"VEGETABLE" NUMBER
	,"VEGETARIAN" NUMBER
	,"VENISON" NUMBER
	,"VERMONT" NUMBER
	,"VERMOUTH" NUMBER
	,"VINEGAR" NUMBER
	,"VIRGINIA" NUMBER
	,"VODKA" NUMBER
	,"WAFFLE" NUMBER
	,"WALNUT" NUMBER
	,"WASABI" NUMBER
	,"WASHINGTON" NUMBER
	,"WASHINGTON_DC" NUMBER
	,"WATERCRESS" NUMBER
	,"WATERMELON" NUMBER
	,"WEDDING" NUMBER
	,"WEELICIOUS" NUMBER
	,"WEST_VIRGINIA" NUMBER
	,"WESTWOOD" NUMBER
	,"WHEAT_GLUTENFREE" NUMBER
	,"WHISKEY" NUMBER
	,"WHITE_WINE" NUMBER
	,"WHOLE_WHEAT" NUMBER
	,"WILD_RICE" NUMBER
	,"WINDSOR" NUMBER
	,"WINE" NUMBER
	,"WINTER" NUMBER
	,"WISCONSIN" NUMBER
	,"WOK" NUMBER
	,"YELLOW_SQUASH" NUMBER
	,"YOGURT" NUMBER
	,"YONKERS" NUMBER
	,"YUCA" NUMBER
	,"ZUCCHINI" NUMBER
	,"COOKBOOKS" NUMBER
	,"LEFTOVERS" NUMBER
	,"SNACK" NUMBER
	,"SNACK_WEEK" NUMBER
	,"TURKEY" NUMBER
	);

CREATE OR REPLACE FORCE VIEW PANTRYDB.RECIPE_V
AS 
WITH T AS (
SELECT 
TRIM(TITLE_ID) AS TITLE_ID
,TRIM(TITLE) AS TITLE
,to_timestamp(CREATED_DATE, 'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"') AS CREATED_DATE
,CATEGORIES
,CALORIES
,DESCRIPTION
,PROTEIN
,RATING
,SODIUM
,SYSTEM_CREATED_AT
,ROW_NUMBER() OVER (PARTITION BY TRIM(TITLE) ORDER BY to_timestamp(CREATED_DATE, 'YYYY-MM-DD"T"HH24:MI:SS.ff3"Z"') ASC) AS RNK
FROM PANTRYDB.RECIPE 
)
SELECT * FROM T WHERE rnk = 1;

CREATE OR REPLACE FORCE VIEW "PANTRYDB"."RECIPE_DIRECTIONS_V" ("TITLE_ID", "SEQ", "NAME", "CREATED_AT") AS 
  SELECT
TRIM(TITLE_ID) AS TITLE_ID
,SEQ
,TRIM(NAME) AS NAME
,CREATED_AT
FROM 	PANTRYDB.RECIPE_DIRECTIONS;

CREATE OR REPLACE FORCE VIEW "PANTRYDB"."RECIPE_INGREDIENTS_V" ("TITLE_ID", "INGREDIENT_ID", "INGREDIENT_NAME", "CREATED_AT") AS 
  SELECT 
TRIM(TITLE_ID) AS TITLE_ID
,INGREDIENT_ID
,TRIM(INGREDIENT_NAME) AS INGREDIENT_NAME
,CREATED_AT
FROM  PANTRYDB.RECIPE_INGREDIENTS;


CREATE OR REPLACE FORCE VIEW "PANTRYDB"."RECIPE_STATS_V" ("TITLE", "RATING", "CALORIES", "PROTEIN", "FAT", "SODIUM", "CAKEWEEK", "WASTELESS", "MINUTE22_MEALS", "INGREDIENT3_RECIPES", "DAYS30_OF_GROCERIES", "ADVANCE_PREP_REQUIRED", "ALABAMA", "ALASKA", "ALCOHOLIC", "ALMOND", "AMARETTO", "ANCHOVY", "ANISE", "ANNIVERSARY", "ANTHONY_BOURDAIN", "APERITIF", "APPETIZER", "APPLE", "APPLE_JUICE", "APRICOT", "ARIZONA", "ARTICHOKE", "ARUGULA", "ASIAN_PEAR", "ASPARAGUS", "ASPEN", "ATLANTA", "AUSTRALIA", "AVOCADO", "BACK_TO_SCHOOL", "BACKYARD_BBQ", "BACON", "BAKE", "BANANA", "BARLEY", "BASIL", "BASS", "BASTILLE_DAY", "BEAN", "BEEF", "BEEF_RIB", "BEEF_SHANK", "BEEF_TENDERLOIN", "BEER", "BEET", "BELL_PEPPER", "BERRY", "BEVERLY_HILLS", "BIRTHDAY", "BISCUIT", "BITTERS", "BLACKBERRY", "BLENDER", "BLUE_CHEESE", "BLUEBERRY", "BOIL", "BOK_CHOY", "BOSTON", "BOURBON", "BRAISE", "BRAN", "BRANDY", "BREAD", "BREADCRUMBS", "BREAKFAST", "BRIE", "BRINE", "BRISKET", "BROCCOLI", "BROCCOLI_RABE", "BROIL", "BROOKLYN", "BROWN_RICE", "BROWNIE", "BRUNCH", "BRUSSEL_SPROUT", "BUFFALO", "BUFFET", "BULGARIA", "BULGUR", "BURRITO", "BUTTER", "BUTTERMILK", "BUTTERNUT_SQUASH", "BUTTERSCOTCH_CARAMEL", "CABBAGE", "CAKE", "CALIFORNIA", "CALVADOS", "CAMBRIDGE", "CAMPARI", "CAMPING", "CANADA", "CANDY", "CANDY_THERMOMETER", "CANTALOUPE", "CAPERS", "CARAWAY", "CARDAMOM", "CARROT", "CASHEW", "CASSEROLE_GRATIN", "CAULIFLOWER", "CAVIAR", "CELERY", "CHAMBORD", "CHAMPAGNE", "CHARD", "CHARTREUSE", "CHEDDAR", "CHEESE", "CHERRY", "CHESTNUT", "CHICAGO", "CHICKEN", "CHICKPEA", "CHILE", "CHILE_PEPPER", "CHILI", "CHILL", "CHIVE", "CHOCOLATE", "CHRISTMAS", "CHRISTMAS_EVE", "CILANTRO", "CINCO_DE_MAYO", "CINNAMON", "CITRUS", "CLAM", "CLOVE", "COBBLER_CRUMBLE", "COCKTAIL", "COCKTAIL_PARTY", "COCONUT", "COD", "COFFEE", "COFFEE_GRINDER", "COGNAC_ARMAGNAC", "COLLARD_GREENS", "COLORADO", "COLUMBUS", "CONDIMENT", "CONDIMENT_SPREAD", "CONNECTICUT", "COOK_LIKE_A_DINER", "COOKBOOK_CRITIC", "COOKIE", "COOKIES", "CORIANDER", "CORN", "CORNMEAL", "COSTA_MESA", "COTTAGE_CHEESE", "COUSCOUS", "CRAB", "CRANBERRY", "CRANBERRY_SAUCE", "CREAM_CHEESE", "CUBA", "CUCUMBER", "CUMIN", "CUPCAKE", "CURRANT", "CURRY", "CUSTARD", "DAIRY", "DAIRY_FREE", "DALLAS", "DATES", "DEEPFRY", "DENVER", "DESSERT", "DIGESTIF", "DILL", "DINNER", "DIP", "DIWALI", "DOMINICAN_REPUBLIC", "DORIE_GREENSPAN", "DOUBLE_BOILER", "DRIED_FRUIT", "DRINK", "DRINKS", "DUCK", "EASTER", "EAU_DE_VIE", "EDIBLE_GIFT", "EGG", "EGG_NOG", "EGGPLANT", "EGYPT", "EMERIL_LAGASSE", "ENDIVE", "ENGAGEMENT_PARTY", "ENGLAND", "ENTERTAINING", "EPI__USHG", "EPI_LOVES_THE_MICROWAVE", "ESCAROLE", "FALL", "FAMILY_REUNION", "FAT_FREE", "FATHERS_DAY", "FENNEL", "FETA", "FIG", "FISH", "FLAMING_HOT_SUMMER", "FLAT_BREAD", "FLORIDA", "FONTINA", "FOOD_PROCESSOR", "FORTIFIED_WINE", "FOURTH_OF_JULY", "FRANCE", "FRANGELICO", "FRANKENRECIPE", "FREEZE_CHILL", "FREEZER_FOOD", "FRIENDSGIVING", "FRITTATA", "FRITTER", "FROZEN_DESSERT", "FRUIT", "FRUIT_JUICE", "FRY", "GAME", "GARLIC", "GEORGIA", "GERMANY", "GIN", "GINGER", "GOAT_CHEESE", "GOOSE", "GOUDA", "GOURMET", "GRADUATION", "GRAINS", "GRAND_MARNIER", "GRANOLA", "GRAPE", "GRAPEFRUIT", "GRAPPA", "GREEN_BEAN", "GREEN_ONION_SCALLION", "GRILL", "GRILL_BARBECUE", "GROUND_BEEF", "GROUND_LAMB", "GUAM", "GUAVA", "HAITI", "HALIBUT", "HALLOWEEN", "HAM", "HAMBURGER", "HANUKKAH", "HARPERCOLLINS", "HAWAII", "HAZELNUT", "HEALDSBURG", "HEALTHY", "HERB", "HIGH_FIBER", "HOLLYWOOD", "HOMINY_CORNMEAL_MASA", "HONEY", "HONEYDEW", "HORS_DOEUVRE", "HORSERADISH", "HOT_DRINK", "HOT_PEPPER", "HOUSE__GARDEN", "HOUSE_COCKTAIL", "HOUSTON", "HUMMUS", "ICE_CREAM", "ICE_CREAM_MACHINE", "ICED_COFFEE", "ICED_TEA", "IDAHO", "ILLINOIS", "INDIANA", "IOWA", "IRELAND", "ISRAEL", "ITALY", "JAM_OR_JELLY", "JAMAICA", "JAPAN", "JERUSALEM_ARTICHOKE", "JUICER", "KALE", "KANSAS", "KANSAS_CITY", "KENTUCKY", "KENTUCKY_DERBY", "KIDFRIENDLY", "KIDNEY_FRIENDLY", "KIRSCH", "KITCHEN_OLYMPICS", "KIWI", "KOSHER", "KOSHER_FOR_PASSOVER", "KUMQUAT", "KWANZAA", "LABOR_DAY", "LAMB", "LAMB_CHOP", "LAMB_SHANK", "LANCASTER", "LAS_VEGAS", "LASAGNA", "LEAFY_GREEN", "LEEK", "LEGUME", "LEMON", "LEMON_JUICE", "LEMONGRASS", "LENTIL", "LETTUCE", "LIMA_BEAN", "LIME", "LIME_JUICE", "LINGONBERRY", "LIQUEUR", "LOBSTER", "LONDON", "LONG_BEACH", "LOS_ANGELES", "LOUISIANA", "LOUISVILLE", "LOW_CAL", "LOW_CARB", "LOW_CHOLESTEROL", "LOW_FAT", "LOW_SODIUM", "LOW_SUGAR", "LOW_NO_SUGAR", "LUNAR_NEW_YEAR", "LUNCH", "LYCHEE", "MACADAMIA_NUT", "MACARONI_AND_CHEESE", "MAINE", "MANDOLINE", "MANGO", "MAPLE_SYRUP", "MARDI_GRAS", "MARGARITA", "MARINADE", "MARINATE", "MARSALA", "MARSCARPONE", "MARSHMALLOW", "MARTINI", "MARYLAND", "MASSACHUSETTS", "MAYONNAISE", "MEAT", "MEATBALL", "MEATLOAF", "MELON", "MEXICO", "MEZCAL", "MIAMI", "MICHIGAN", "MICROWAVE", "MIDORI", "MILK_CREAM", "MINNEAPOLIS", "MINNESOTA", "MINT", "MISSISSIPPI", "MISSOURI", "MIXER", "MOLASSES", "MONTEREY_JACK", "MORTAR_AND_PESTLE", "MOTHERS_DAY", "MOZZARELLA", "MUFFIN", "MUSHROOM", "MUSSEL", "MUSTARD", "MUSTARD_GREENS", "NANCY_SILVERTON", "NEBRASKA", "NECTARINE", "NEW_HAMPSHIRE", "NEW_JERSEY", "NEW_MEXICO", "NEW_ORLEANS", "NEW_YEARS_DAY", "NEW_YEARS_EVE", "NEW_YORK", "NO_MEAT_NO_PROBLEM", "NO_SUGAR_ADDED", "NOCOOK", "NONALCOHOLIC", "NOODLE", "NORTH_CAROLINA", "NUT", "NUTMEG", "OAT", "OATMEAL", "OCTOPUS", "OHIO", "OKLAHOMA", "OKRA", "OKTOBERFEST", "OLIVE", "OMELET", "ONEPOT_MEAL", "ONION", "ORANGE", "ORANGE_JUICE", "OREGANO", "OREGON", "ORGANIC", "ORZO", "OSCARS", "OYSTER", "PACIFIC_PALISADES", "PALEO", "PANFRY", "PANCAKE", "PAPAYA", "PAPRIKA", "PARADE", "PARIS", "PARMESAN", "PARSLEY", "PARSNIP", "PARTY", "PASADENA", "PASSION_FRUIT", "PASSOVER", "PASTA", "PASTA_MAKER", "PASTRY", "PEA", "PEACH", "PEANUT", "PEANUT_BUTTER", "PEANUT_FREE", "PEAR", "PECAN", "PENNSYLVANIA", "PEPPER", "PERNOD", "PERSIAN_NEW_YEAR", "PERSIMMON", "PERU", "PESCATARIAN", "PHILIPPINES", "PHYLLO_PUFF_PASTRY_DOUGH", "PICKLES", "PICNIC", "PIE", "PINE_NUT", "PINEAPPLE", "PISTACHIO", "PITTSBURGH", "PIZZA", "PLANTAIN", "PLUM", "POACH", "POBLANO", "POKER_GAME_NIGHT", "POMEGRANATE", "POMEGRANATE_JUICE", "POPPY", "PORK", "PORK_CHOP", "PORK_RIB", "PORK_TENDERLOIN", "PORT", "PORTLAND", "POT_PIE", "POTATO", "POTATO_SALAD", "POTLUCK", "POULTRY", "POULTRY_SAUSAGE", "PRESSURE_COOKER", "PROSCIUTTO", "PROVIDENCE", "PRUNE", "PUMPKIN", "PUNCH", "PURIM", "QUAIL", "QUICHE", "QUICK__EASY", "QUICK_AND_HEALTHY", "QUINCE", "QUINOA", "RABBIT", "RACK_OF_LAMB", "RADICCHIO", "RADISH", "RAISIN", "RAMADAN", "RAMEKIN", "RASPBERRY", "RAW_", "RED_WINE", "RHODE_ISLAND", "RHUBARB", "RICE", "RICOTTA", "ROAST", "ROOT_VEGETABLE", "ROSEMARY", "ROSH_HASHANAH_YOM_KIPPUR", "RUB", "RUM", "RUTABAGA", "RYE", "SAFFRON", "SAGE", "SAKE", "SALAD", "SALAD_DRESSING", "SALMON", "SALSA", "SAN_FRANCISCO", "SANDWICH", "SANDWICH_THEORY", "SANGRIA", "SANTA_MONICA", "SARDINE", "SAUCE", "SAUSAGE", "SCALLOP", "SCOTCH", "SEAFOOD", "SEATTLE", "SEED", "SELF_", "SEMOLINA", "SESAME", "SESAME_OIL", "SHALLOT", "SHAVUOT", "SHELLFISH", "SHERRY", "SHOWER", "SHRIMP", "SIDE", "SIMMER", "SKEWER", "SLOW_COOKER", "SMOKER", "SMOOTHIE", "SNAPPER", "SORBET", "SOUFFL_MERINGUE", "SOUP_STEW", "SOUR_CREAM", "SOURDOUGH", "SOUTH_CAROLINA", "SOY", "SOY_FREE", "SOY_SAUCE", "SPAIN", "SPARKLING_WINE", "SPICE", "SPINACH", "SPIRIT", "SPRING", "SPRITZER", "SQUASH", "SQUID", "ST_LOUIS", "ST_PATRICKS_DAY", "STEAK", "STEAM", "STEW", "STIRFRY", "STOCK", "STRAWBERRY", "STUFFING_DRESSING", "SUGAR_CONSCIOUS", "SUGAR_SNAP_PEA", "SUKKOT", "SUMMER", "SUPER_BOWL", "SUZANNE_GOIN", "SWEET_POTATO_YAM", "SWISS_CHEESE", "SWITZERLAND", "SWORDFISH", "TACO", "TAILGATING", "TAMARIND", "TANGERINE", "TAPIOCA", "TARRAGON", "TART", "TEA", "TENNESSEE", "TEQUILA", "TESTED__IMPROVED", "TEXAS", "THANKSGIVING", "THYME", "TILAPIA", "TOFU", "TOMATILLO", "TOMATO", "TORTILLAS", "TREE_NUT", "TREE_NUT_FREE", "TRIPLE_SEC", "TROPICAL_FRUIT", "TROUT", "TUNA", "TURNIP", "UTAH", "VALENTINES_DAY", "VANILLA", "VEAL", "VEGAN", "VEGETABLE", "VEGETARIAN", "VENISON", "VERMONT", "VERMOUTH", "VINEGAR", "VIRGINIA", "VODKA", "WAFFLE", "WALNUT", "WASABI", "WASHINGTON", "WASHINGTON_DC", "WATERCRESS", "WATERMELON", "WEDDING", "WEELICIOUS", "WEST_VIRGINIA", "WESTWOOD", "WHEAT_GLUTENFREE", "WHISKEY", "WHITE_WINE", "WHOLE_WHEAT", "WILD_RICE", "WINDSOR", "WINE", "WINTER", "WISCONSIN", "WOK", "YELLOW_SQUASH", "YOGURT", "YONKERS", "YUCA", "ZUCCHINI", "COOKBOOKS", "LEFTOVERS", "SNACK", "SNACK_WEEK", "TURKEY") AS 
  SELECT
TRIM(TITLE) AS TITLE,
TO_NUMBER(RATING) AS RATING,
TO_NUMBER(CALORIES) AS CALORIES,
TO_NUMBER(PROTEIN) AS PROTEIN,
TO_NUMBER(FAT) AS FAT,
TO_NUMBER(SODIUM) AS SODIUM,
TO_NUMBER(CAKEWEEK) AS CAKEWEEK,
TO_NUMBER(WASTELESS) AS WASTELESS,
TO_NUMBER(MINUTE22_MEALS) AS MINUTE22_MEALS,
TO_NUMBER(INGREDIENT3_RECIPES) AS INGREDIENT3_RECIPES,
TO_NUMBER(DAYS30_OF_GROCERIES) AS DAYS30_OF_GROCERIES,
TO_NUMBER(ADVANCE_PREP_REQUIRED) AS ADVANCE_PREP_REQUIRED,
TO_NUMBER(ALABAMA) AS ALABAMA,
TO_NUMBER(ALASKA) AS ALASKA,
TO_NUMBER(ALCOHOLIC) AS ALCOHOLIC,
TO_NUMBER(ALMOND) AS ALMOND,
TO_NUMBER(AMARETTO) AS AMARETTO,
TO_NUMBER(ANCHOVY) AS ANCHOVY,
TO_NUMBER(ANISE) AS ANISE,
TO_NUMBER(ANNIVERSARY) AS ANNIVERSARY,
TO_NUMBER(ANTHONY_BOURDAIN) AS ANTHONY_BOURDAIN,
TO_NUMBER(APERITIF) AS APERITIF,
TO_NUMBER(APPETIZER) AS APPETIZER,
TO_NUMBER(APPLE) AS APPLE,
TO_NUMBER(APPLE_JUICE) AS APPLE_JUICE,
TO_NUMBER(APRICOT) AS APRICOT,
TO_NUMBER(ARIZONA) AS ARIZONA,
TO_NUMBER(ARTICHOKE) AS ARTICHOKE,
TO_NUMBER(ARUGULA) AS ARUGULA,
TO_NUMBER(ASIAN_PEAR) AS ASIAN_PEAR,
TO_NUMBER(ASPARAGUS) AS ASPARAGUS,
TO_NUMBER(ASPEN) AS ASPEN,
TO_NUMBER(ATLANTA) AS ATLANTA,
TO_NUMBER(AUSTRALIA) AS AUSTRALIA,
TO_NUMBER(AVOCADO) AS AVOCADO,
TO_NUMBER(BACK_TO_SCHOOL) AS BACK_TO_SCHOOL,
TO_NUMBER(BACKYARD_BBQ) AS BACKYARD_BBQ,
TO_NUMBER(BACON) AS BACON,
TO_NUMBER(BAKE) AS BAKE,
TO_NUMBER(BANANA) AS BANANA,
TO_NUMBER(BARLEY) AS BARLEY,
TO_NUMBER(BASIL) AS BASIL,
TO_NUMBER(BASS) AS BASS,
TO_NUMBER(BASTILLE_DAY) AS BASTILLE_DAY,
TO_NUMBER(BEAN) AS BEAN,
TO_NUMBER(BEEF) AS BEEF,
TO_NUMBER(BEEF_RIB) AS BEEF_RIB,
TO_NUMBER(BEEF_SHANK) AS BEEF_SHANK,
TO_NUMBER(BEEF_TENDERLOIN) AS BEEF_TENDERLOIN,
TO_NUMBER(BEER) AS BEER,
TO_NUMBER(BEET) AS BEET,
TO_NUMBER(BELL_PEPPER) AS BELL_PEPPER,
TO_NUMBER(BERRY) AS BERRY,
TO_NUMBER(BEVERLY_HILLS) AS BEVERLY_HILLS,
TO_NUMBER(BIRTHDAY) AS BIRTHDAY,
TO_NUMBER(BISCUIT) AS BISCUIT,
TO_NUMBER(BITTERS) AS BITTERS,
TO_NUMBER(BLACKBERRY) AS BLACKBERRY,
TO_NUMBER(BLENDER) AS BLENDER,
TO_NUMBER(BLUE_CHEESE) AS BLUE_CHEESE,
TO_NUMBER(BLUEBERRY) AS BLUEBERRY,
TO_NUMBER(BOIL) AS BOIL,
TO_NUMBER(BOK_CHOY) AS BOK_CHOY,
TO_NUMBER(BOSTON) AS BOSTON,
TO_NUMBER(BOURBON) AS BOURBON,
TO_NUMBER(BRAISE) AS BRAISE,
TO_NUMBER(BRAN) AS BRAN,
TO_NUMBER(BRANDY) AS BRANDY,
TO_NUMBER(BREAD) AS BREAD,
TO_NUMBER(BREADCRUMBS) AS BREADCRUMBS,
TO_NUMBER(BREAKFAST) AS BREAKFAST,
TO_NUMBER(BRIE) AS BRIE,
TO_NUMBER(BRINE) AS BRINE,
TO_NUMBER(BRISKET) AS BRISKET,
TO_NUMBER(BROCCOLI) AS BROCCOLI,
TO_NUMBER(BROCCOLI_RABE) AS BROCCOLI_RABE,
TO_NUMBER(BROIL) AS BROIL,
TO_NUMBER(BROOKLYN) AS BROOKLYN,
TO_NUMBER(BROWN_RICE) AS BROWN_RICE,
TO_NUMBER(BROWNIE) AS BROWNIE,
TO_NUMBER(BRUNCH) AS BRUNCH,
TO_NUMBER(BRUSSEL_SPROUT) AS BRUSSEL_SPROUT,
TO_NUMBER(BUFFALO) AS BUFFALO,
TO_NUMBER(BUFFET) AS BUFFET,
TO_NUMBER(BULGARIA) AS BULGARIA,
TO_NUMBER(BULGUR) AS BULGUR,
TO_NUMBER(BURRITO) AS BURRITO,
TO_NUMBER(BUTTER) AS BUTTER,
TO_NUMBER(BUTTERMILK) AS BUTTERMILK,
TO_NUMBER(BUTTERNUT_SQUASH) AS BUTTERNUT_SQUASH,
TO_NUMBER(BUTTERSCOTCH_CARAMEL) AS BUTTERSCOTCH_CARAMEL ,
TO_NUMBER(CABBAGE) AS CABBAGE,
TO_NUMBER(CAKE) AS CAKE,
TO_NUMBER(CALIFORNIA) AS CALIFORNIA,
TO_NUMBER(CALVADOS) AS CALVADOS,
TO_NUMBER(CAMBRIDGE) AS CAMBRIDGE,
TO_NUMBER(CAMPARI) AS CAMPARI,
TO_NUMBER(CAMPING) AS CAMPING,
TO_NUMBER(CANADA) AS CANADA,
TO_NUMBER(CANDY) AS CANDY,
TO_NUMBER(CANDY_THERMOMETER) AS CANDY_THERMOMETER,
TO_NUMBER(CANTALOUPE) AS CANTALOUPE,
TO_NUMBER(CAPERS) AS CAPERS,
TO_NUMBER(CARAWAY) AS CARAWAY,
TO_NUMBER(CARDAMOM) AS CARDAMOM,
TO_NUMBER(CARROT) AS CARROT,
TO_NUMBER(CASHEW) AS CASHEW,
TO_NUMBER(CASSEROLE_GRATIN) AS CASSEROLE_GRATIN,
TO_NUMBER(CAULIFLOWER) AS CAULIFLOWER,
TO_NUMBER(CAVIAR) AS CAVIAR,
TO_NUMBER(CELERY) AS CELERY,
TO_NUMBER(CHAMBORD) AS CHAMBORD,
TO_NUMBER(CHAMPAGNE) AS CHAMPAGNE,
TO_NUMBER(CHARD) AS CHARD,
TO_NUMBER(CHARTREUSE) AS CHARTREUSE,
TO_NUMBER(CHEDDAR) AS CHEDDAR,
TO_NUMBER(CHEESE) AS CHEESE,
TO_NUMBER(CHERRY) AS CHERRY,
TO_NUMBER(CHESTNUT) AS CHESTNUT,
TO_NUMBER(CHICAGO) AS CHICAGO,
TO_NUMBER(CHICKEN) AS CHICKEN,
TO_NUMBER(CHICKPEA) AS CHICKPEA,
TO_NUMBER(CHILE) AS CHILE,
TO_NUMBER(CHILE_PEPPER) AS CHILE_PEPPER,
TO_NUMBER(CHILI) AS CHILI,
TO_NUMBER(CHILL) AS CHILL,
TO_NUMBER(CHIVE) AS CHIVE,
TO_NUMBER(CHOCOLATE) AS CHOCOLATE,
TO_NUMBER(CHRISTMAS) AS CHRISTMAS,
TO_NUMBER(CHRISTMAS_EVE) AS CHRISTMAS_EVE,
TO_NUMBER(CILANTRO) AS CILANTRO,
TO_NUMBER(CINCO_DE_MAYO) AS CINCO_DE_MAYO,
TO_NUMBER(CINNAMON) AS CINNAMON,
TO_NUMBER(CITRUS) AS CITRUS,
TO_NUMBER(CLAM) AS CLAM,
TO_NUMBER(CLOVE) AS CLOVE,
TO_NUMBER(COBBLER_CRUMBLE) AS COBBLER_CRUMBLE,
TO_NUMBER(COCKTAIL) AS COCKTAIL,
TO_NUMBER(COCKTAIL_PARTY) AS COCKTAIL_PARTY,
TO_NUMBER(COCONUT) AS COCONUT,
TO_NUMBER(COD) AS COD,
TO_NUMBER(COFFEE) AS COFFEE,
TO_NUMBER(COFFEE_GRINDER) AS COFFEE_GRINDER,
TO_NUMBER(COGNAC_ARMAGNAC) AS COGNAC_ARMAGNAC,
TO_NUMBER(COLLARD_GREENS) AS COLLARD_GREENS,
TO_NUMBER(COLORADO) AS COLORADO,
TO_NUMBER(COLUMBUS) AS COLUMBUS,
TO_NUMBER(CONDIMENT) AS CONDIMENT,
TO_NUMBER(CONDIMENT_SPREAD) AS CONDIMENT_SPREAD,
TO_NUMBER(CONNECTICUT) AS CONNECTICUT,
TO_NUMBER(COOK_LIKE_A_DINER) AS COOK_LIKE_A_DINER,
TO_NUMBER(COOKBOOK_CRITIC) AS COOKBOOK_CRITIC,
TO_NUMBER(COOKIE) AS COOKIE,
TO_NUMBER(COOKIES) AS COOKIES,
TO_NUMBER(CORIANDER) AS CORIANDER,
TO_NUMBER(CORN) AS CORN,
TO_NUMBER(CORNMEAL) AS CORNMEAL,
TO_NUMBER(COSTA_MESA) AS COSTA_MESA,
TO_NUMBER(COTTAGE_CHEESE) AS COTTAGE_CHEESE,
TO_NUMBER(COUSCOUS) AS COUSCOUS,
TO_NUMBER(CRAB) AS CRAB,
TO_NUMBER(CRANBERRY) AS CRANBERRY,
TO_NUMBER(CRANBERRY_SAUCE) AS CRANBERRY_SAUCE,
TO_NUMBER(CREAM_CHEESE) AS CREAM_CHEESE,
TO_NUMBER(CUBA) AS CUBA,
TO_NUMBER(CUCUMBER) AS CUCUMBER,
TO_NUMBER(CUMIN) AS CUMIN,
TO_NUMBER(CUPCAKE) AS CUPCAKE,
TO_NUMBER(CURRANT) AS CURRANT,
TO_NUMBER(CURRY) AS CURRY,
TO_NUMBER(CUSTARD) AS CUSTARD,
TO_NUMBER(DAIRY) AS DAIRY,
TO_NUMBER(DAIRY_FREE) AS DAIRY_FREE,
TO_NUMBER(DALLAS) AS DALLAS,
TO_NUMBER(DATES) AS DATES,
TO_NUMBER(DEEPFRY) AS DEEPFRY,
TO_NUMBER(DENVER) AS DENVER,
TO_NUMBER(DESSERT) AS DESSERT,
TO_NUMBER(DIGESTIF) AS DIGESTIF,
TO_NUMBER(DILL) AS DILL,
TO_NUMBER(DINNER) AS DINNER,
TO_NUMBER(DIP) AS DIP,
TO_NUMBER(DIWALI) AS DIWALI,
TO_NUMBER(DOMINICAN_REPUBLIC) AS DOMINICAN_REPUBLIC,
TO_NUMBER(DORIE_GREENSPAN) AS DORIE_GREENSPAN,
TO_NUMBER(DOUBLE_BOILER) AS DOUBLE_BOILER,
TO_NUMBER(DRIED_FRUIT) AS DRIED_FRUIT,
TO_NUMBER(DRINK) AS DRINK,
TO_NUMBER(DRINKS) AS DRINKS,
TO_NUMBER(DUCK) AS DUCK,
TO_NUMBER(EASTER) AS EASTER,
TO_NUMBER(EAU_DE_VIE) AS EAU_DE_VIE,
TO_NUMBER(EDIBLE_GIFT) AS EDIBLE_GIFT,
TO_NUMBER(EGG) AS EGG,
TO_NUMBER(EGG_NOG) AS EGG_NOG,
TO_NUMBER(EGGPLANT) AS EGGPLANT,
TO_NUMBER(EGYPT) AS EGYPT,
TO_NUMBER(EMERIL_LAGASSE) AS EMERIL_LAGASSE,
TO_NUMBER(ENDIVE) AS ENDIVE,
TO_NUMBER(ENGAGEMENT_PARTY) AS ENGAGEMENT_PARTY,
TO_NUMBER(ENGLAND) AS ENGLAND,
TO_NUMBER(ENTERTAINING) AS ENTERTAINING,
TO_NUMBER(EPI__USHG) AS EPI__USHG,
TO_NUMBER(EPI_LOVES_THE_MICROWAVE) AS EPI_LOVES_THE_MICROWAVE,
TO_NUMBER(ESCAROLE) AS ESCAROLE,
TO_NUMBER(FALL) AS FALL,
TO_NUMBER(FAMILY_REUNION) AS FAMILY_REUNION,
TO_NUMBER(FAT_FREE) AS FAT_FREE,
TO_NUMBER(FATHERS_DAY) AS FATHERS_DAY,
TO_NUMBER(FENNEL) AS FENNEL,
TO_NUMBER(FETA) AS FETA,
TO_NUMBER(FIG) AS FIG,
TO_NUMBER(FISH) AS FISH,
TO_NUMBER(FLAMING_HOT_SUMMER) AS FLAMING_HOT_SUMMER,
TO_NUMBER(FLAT_BREAD) AS FLAT_BREAD,
TO_NUMBER(FLORIDA) AS FLORIDA,
TO_NUMBER(FONTINA) AS FONTINA,
TO_NUMBER(FOOD_PROCESSOR) AS FOOD_PROCESSOR,
TO_NUMBER(FORTIFIED_WINE) AS FORTIFIED_WINE,
TO_NUMBER(FOURTH_OF_JULY) AS FOURTH_OF_JULY,
TO_NUMBER(FRANCE) AS FRANCE,
TO_NUMBER(FRANGELICO) AS FRANGELICO,
TO_NUMBER(FRANKENRECIPE) AS FRANKENRECIPE,
TO_NUMBER(FREEZE_CHILL) AS FREEZE_CHILL,
TO_NUMBER(FREEZER_FOOD) AS FREEZER_FOOD,
TO_NUMBER(FRIENDSGIVING) AS FRIENDSGIVING,
TO_NUMBER(FRITTATA) AS FRITTATA,
TO_NUMBER(FRITTER) AS FRITTER,
TO_NUMBER(FROZEN_DESSERT) AS FROZEN_DESSERT,
TO_NUMBER(FRUIT) AS FRUIT,
TO_NUMBER(FRUIT_JUICE) AS FRUIT_JUICE,
TO_NUMBER(FRY) AS FRY,
TO_NUMBER(GAME) AS GAME,
TO_NUMBER(GARLIC) AS GARLIC,
TO_NUMBER(GEORGIA) AS GEORGIA,
TO_NUMBER(GERMANY) AS GERMANY,
TO_NUMBER(GIN) AS GIN,
TO_NUMBER(GINGER) AS GINGER,
TO_NUMBER(GOAT_CHEESE) AS GOAT_CHEESE,
TO_NUMBER(GOOSE) AS GOOSE,
TO_NUMBER(GOUDA) AS GOUDA,
TO_NUMBER(GOURMET) AS GOURMET,
TO_NUMBER(GRADUATION) AS GRADUATION,
TO_NUMBER(GRAINS) AS GRAINS,
TO_NUMBER(GRAND_MARNIER) AS GRAND_MARNIER,
TO_NUMBER(GRANOLA) AS GRANOLA,
TO_NUMBER(GRAPE) AS GRAPE,
TO_NUMBER(GRAPEFRUIT) AS GRAPEFRUIT,
TO_NUMBER(GRAPPA) AS GRAPPA,
TO_NUMBER(GREEN_BEAN) AS GREEN_BEAN,
TO_NUMBER(GREEN_ONION_SCALLION) AS GREEN_ONION_SCALLION,
TO_NUMBER(GRILL) AS GRILL,
TO_NUMBER(GRILL_BARBECUE) AS GRILL_BARBECUE,
TO_NUMBER(GROUND_BEEF) AS GROUND_BEEF,
TO_NUMBER(GROUND_LAMB) AS GROUND_LAMB,
TO_NUMBER(GUAM) AS GUAM,
TO_NUMBER(GUAVA) AS GUAVA ,
TO_NUMBER(HAITI) AS HAITI,
TO_NUMBER(HALIBUT) AS HALIBUT,
TO_NUMBER(HALLOWEEN) AS HALLOWEEN,
TO_NUMBER(HAM) AS HAM,
TO_NUMBER(HAMBURGER) AS HAMBURGER,
TO_NUMBER(HANUKKAH) AS HANUKKAH,
TO_NUMBER(HARPERCOLLINS) AS HARPERCOLLINS,
TO_NUMBER(HAWAII) AS HAWAII,
TO_NUMBER(HAZELNUT) AS HAZELNUT,
TO_NUMBER(HEALDSBURG) AS HEALDSBURG,
TO_NUMBER(HEALTHY) AS HEALTHY,
TO_NUMBER(HERB) AS HERB,
TO_NUMBER(HIGH_FIBER) AS HIGH_FIBER,
TO_NUMBER(HOLLYWOOD) AS HOLLYWOOD,
TO_NUMBER(HOMINY_CORNMEAL_MASA) AS HOMINY_CORNMEAL_MASA,
TO_NUMBER(HONEY) AS HONEY,
TO_NUMBER(HONEYDEW) AS HONEYDEW,
TO_NUMBER(HORS_DOEUVRE) AS HORS_DOEUVRE,
TO_NUMBER(HORSERADISH) AS HORSERADISH,
TO_NUMBER(HOT_DRINK) AS HOT_DRINK,
TO_NUMBER(HOT_PEPPER) AS HOT_PEPPER,
TO_NUMBER(HOUSE__GARDEN) AS HOUSE__GARDEN,
TO_NUMBER(HOUSE_COCKTAIL) AS HOUSE_COCKTAIL,
TO_NUMBER(HOUSTON) AS HOUSTON,
TO_NUMBER(HUMMUS) AS HUMMUS ,
TO_NUMBER(ICE_CREAM) AS ICE_CREAM,
TO_NUMBER(ICE_CREAM_MACHINE) AS ICE_CREAM_MACHINE,
TO_NUMBER(ICED_COFFEE) AS ICED_COFFEE,
TO_NUMBER(ICED_TEA) AS ICED_TEA,
TO_NUMBER(IDAHO) AS IDAHO,
TO_NUMBER(ILLINOIS) AS ILLINOIS,
TO_NUMBER(INDIANA) AS INDIANA,
TO_NUMBER(IOWA) AS IOWA,
TO_NUMBER(IRELAND) AS IRELAND,
TO_NUMBER(ISRAEL) AS ISRAEL,
TO_NUMBER(ITALY) AS ITALY,
TO_NUMBER(JAM_OR_JELLY) AS JAM_OR_JELLY,
TO_NUMBER(JAMAICA) AS JAMAICA,
TO_NUMBER(JAPAN) AS JAPAN,
TO_NUMBER(JERUSALEM_ARTICHOKE) AS JERUSALEM_ARTICHOKE,
TO_NUMBER(JUICER) AS JUICER,
TO_NUMBER(KALE) AS KALE,
TO_NUMBER(KANSAS) AS KANSAS,
TO_NUMBER(KANSAS_CITY) AS KANSAS_CITY,
TO_NUMBER(KENTUCKY) AS KENTUCKY,
TO_NUMBER(KENTUCKY_DERBY) AS KENTUCKY_DERBY,
TO_NUMBER(KIDFRIENDLY) AS KIDFRIENDLY,
TO_NUMBER(KIDNEY_FRIENDLY) AS KIDNEY_FRIENDLY,
TO_NUMBER(KIRSCH) AS KIRSCH,
TO_NUMBER(KITCHEN_OLYMPICS) AS KITCHEN_OLYMPICS,
TO_NUMBER(KIWI) AS KIWI,
TO_NUMBER(KOSHER) AS KOSHER,
TO_NUMBER(KOSHER_FOR_PASSOVER) AS KOSHER_FOR_PASSOVER,
TO_NUMBER(KUMQUAT) AS KUMQUAT,
TO_NUMBER(KWANZAA) AS KWANZAA,
TO_NUMBER(LABOR_DAY) AS LABOR_DAY,
TO_NUMBER(LAMB) AS LAMB,
TO_NUMBER(LAMB_CHOP) AS LAMB_CHOP,
TO_NUMBER(LAMB_SHANK) AS LAMB_SHANK,
TO_NUMBER(LANCASTER) AS LANCASTER,
TO_NUMBER(LAS_VEGAS) AS LAS_VEGAS,
TO_NUMBER(LASAGNA) AS LASAGNA,
TO_NUMBER(LEAFY_GREEN) AS LEAFY_GREEN,
TO_NUMBER(LEEK) AS LEEK,
TO_NUMBER(LEGUME) AS LEGUME,
TO_NUMBER(LEMON) AS LEMON,
TO_NUMBER(LEMON_JUICE) AS LEMON_JUICE,
TO_NUMBER(LEMONGRASS) AS LEMONGRASS,
TO_NUMBER(LENTIL) AS LENTIL,
TO_NUMBER(LETTUCE) AS LETTUCE,
TO_NUMBER(LIMA_BEAN) AS LIMA_BEAN,
TO_NUMBER(LIME) AS LIME,
TO_NUMBER(LIME_JUICE) AS LIME_JUICE,
TO_NUMBER(LINGONBERRY) AS LINGONBERRY,
TO_NUMBER(LIQUEUR) AS LIQUEUR,
TO_NUMBER(LOBSTER) AS LOBSTER,
TO_NUMBER(LONDON) AS LONDON,
TO_NUMBER(LONG_BEACH) AS LONG_BEACH,
TO_NUMBER(LOS_ANGELES) AS LOS_ANGELES,
TO_NUMBER(LOUISIANA) AS LOUISIANA,
TO_NUMBER(LOUISVILLE) AS LOUISVILLE,
TO_NUMBER(LOW_CAL) AS LOW_CAL,
TO_NUMBER(LOW_CARB) AS LOW_CARB,
TO_NUMBER(LOW_CHOLESTEROL) AS LOW_CHOLESTEROL,
TO_NUMBER(LOW_FAT) AS LOW_FAT,
TO_NUMBER(LOW_SODIUM) AS LOW_SODIUM,
TO_NUMBER(LOW_SUGAR) AS LOW_SUGAR,
TO_NUMBER(LOW_NO_SUGAR) AS LOW_NO_SUGAR,
TO_NUMBER(LUNAR_NEW_YEAR) AS LUNAR_NEW_YEAR,
TO_NUMBER(LUNCH) AS LUNCH,
TO_NUMBER(LYCHEE) AS LYCHEE ,
TO_NUMBER(MACADAMIA_NUT) AS MACADAMIA_NUT,
TO_NUMBER(MACARONI_AND_CHEESE) AS MACARONI_AND_CHEESE,
TO_NUMBER(MAINE) AS MAINE,
TO_NUMBER(MANDOLINE) AS MANDOLINE,
TO_NUMBER(MANGO) AS MANGO,
TO_NUMBER(MAPLE_SYRUP) AS MAPLE_SYRUP,
TO_NUMBER(MARDI_GRAS) AS MARDI_GRAS,
TO_NUMBER(MARGARITA) AS MARGARITA,
TO_NUMBER(MARINADE) AS MARINADE,
TO_NUMBER(MARINATE) AS MARINATE,
TO_NUMBER(MARSALA) AS MARSALA,
TO_NUMBER(MARSCARPONE) AS MARSCARPONE,
TO_NUMBER(MARSHMALLOW) AS MARSHMALLOW,
TO_NUMBER(MARTINI) AS MARTINI,
TO_NUMBER(MARYLAND) AS MARYLAND,
TO_NUMBER(MASSACHUSETTS) AS MASSACHUSETTS,
TO_NUMBER(MAYONNAISE) AS MAYONNAISE,
TO_NUMBER(MEAT) AS MEAT,
TO_NUMBER(MEATBALL) AS MEATBALL,
TO_NUMBER(MEATLOAF) AS MEATLOAF,
TO_NUMBER(MELON) AS MELON,
TO_NUMBER(MEXICO) AS MEXICO,
TO_NUMBER(MEZCAL) AS MEZCAL,
TO_NUMBER(MIAMI) AS MIAMI,
TO_NUMBER(MICHIGAN) AS MICHIGAN,
TO_NUMBER(MICROWAVE) AS MICROWAVE,
TO_NUMBER(MIDORI) AS MIDORI,
TO_NUMBER(MILK_CREAM) AS MILK_CREAM,
TO_NUMBER(MINNEAPOLIS) AS MINNEAPOLIS,
TO_NUMBER(MINNESOTA) AS MINNESOTA,
TO_NUMBER(MINT) AS MINT,
TO_NUMBER(MISSISSIPPI) AS MISSISSIPPI,
TO_NUMBER(MISSOURI) AS MISSOURI,
TO_NUMBER(MIXER) AS MIXER,
TO_NUMBER(MOLASSES) AS MOLASSES,
TO_NUMBER(MONTEREY_JACK) AS MONTEREY_JACK,
TO_NUMBER(MORTAR_AND_PESTLE) AS MORTAR_AND_PESTLE,
TO_NUMBER(MOTHERS_DAY) AS MOTHERS_DAY,
TO_NUMBER(MOZZARELLA) AS MOZZARELLA,
TO_NUMBER(MUFFIN) AS MUFFIN,
TO_NUMBER(MUSHROOM) AS MUSHROOM,
TO_NUMBER(MUSSEL) AS MUSSEL,
TO_NUMBER(MUSTARD) AS MUSTARD,
TO_NUMBER(MUSTARD_GREENS) AS MUSTARD_GREENS,
TO_NUMBER(NANCY_SILVERTON) AS NANCY_SILVERTON,
TO_NUMBER(NEBRASKA) AS NEBRASKA,
TO_NUMBER(NECTARINE) AS NECTARINE,
TO_NUMBER(NEW_HAMPSHIRE) AS NEW_HAMPSHIRE,
TO_NUMBER(NEW_JERSEY) AS NEW_JERSEY,
TO_NUMBER(NEW_MEXICO) AS NEW_MEXICO,
TO_NUMBER(NEW_ORLEANS) AS NEW_ORLEANS,
TO_NUMBER(NEW_YEARS_DAY) AS NEW_YEARS_DAY,
TO_NUMBER(NEW_YEARS_EVE) AS NEW_YEARS_EVE,
TO_NUMBER(NEW_YORK) AS NEW_YORK,
TO_NUMBER(NO_MEAT_NO_PROBLEM) AS NO_MEAT_NO_PROBLEM,
TO_NUMBER(NO_SUGAR_ADDED) AS NO_SUGAR_ADDED,
TO_NUMBER(NOCOOK) AS NOCOOK,
TO_NUMBER(NONALCOHOLIC) AS NONALCOHOLIC,
TO_NUMBER(NOODLE) AS NOODLE,
TO_NUMBER(NORTH_CAROLINA) AS NORTH_CAROLINA,
TO_NUMBER(NUT) AS NUT,
TO_NUMBER(NUTMEG) AS NUTMEG,
TO_NUMBER(OAT) AS OAT,
TO_NUMBER(OATMEAL) AS OATMEAL,
TO_NUMBER(OCTOPUS) AS OCTOPUS,
TO_NUMBER(OHIO) AS OHIO,
TO_NUMBER(OKLAHOMA) AS OKLAHOMA,
TO_NUMBER(OKRA) AS OKRA,
TO_NUMBER(OKTOBERFEST) AS OKTOBERFEST,
TO_NUMBER(OLIVE) AS OLIVE,
TO_NUMBER(OMELET) AS OMELET,
TO_NUMBER(ONEPOT_MEAL) AS ONEPOT_MEAL,
TO_NUMBER(ONION) AS ONION,
TO_NUMBER(ORANGE) AS ORANGE,
TO_NUMBER(ORANGE_JUICE) AS ORANGE_JUICE,
TO_NUMBER(OREGANO) AS OREGANO,
TO_NUMBER(OREGON) AS OREGON,
TO_NUMBER(ORGANIC) AS ORGANIC,
TO_NUMBER(ORZO) AS ORZO,
TO_NUMBER(OSCARS) AS OSCARS,
TO_NUMBER(OYSTER) AS OYSTER,
TO_NUMBER(PACIFIC_PALISADES) AS PACIFIC_PALISADES,
TO_NUMBER(PALEO) AS PALEO,
TO_NUMBER(PANFRY) AS PANFRY,
TO_NUMBER(PANCAKE) AS PANCAKE,
TO_NUMBER(PAPAYA) AS PAPAYA,
TO_NUMBER(PAPRIKA) AS PAPRIKA,
TO_NUMBER(PARADE) AS PARADE,
TO_NUMBER(PARIS) AS PARIS,
TO_NUMBER(PARMESAN) AS PARMESAN,
TO_NUMBER(PARSLEY) AS PARSLEY,
TO_NUMBER(PARSNIP) AS PARSNIP,
TO_NUMBER(PARTY) AS PARTY,
TO_NUMBER(PASADENA) AS PASADENA,
TO_NUMBER(PASSION_FRUIT) AS PASSION_FRUIT,
TO_NUMBER(PASSOVER) AS PASSOVER,
TO_NUMBER(PASTA) AS PASTA,
TO_NUMBER(PASTA_MAKER) AS PASTA_MAKER,
TO_NUMBER(PASTRY) AS PASTRY,
TO_NUMBER(PEA) AS PEA,
TO_NUMBER(PEACH) AS PEACH,
TO_NUMBER(PEANUT) AS PEANUT,
TO_NUMBER(PEANUT_BUTTER) AS PEANUT_BUTTER,
TO_NUMBER(PEANUT_FREE) AS PEANUT_FREE,
TO_NUMBER(PEAR) AS PEAR,
TO_NUMBER(PECAN) AS PECAN,
TO_NUMBER(PENNSYLVANIA) AS PENNSYLVANIA,
TO_NUMBER(PEPPER) AS PEPPER,
TO_NUMBER(PERNOD) AS PERNOD,
TO_NUMBER(PERSIAN_NEW_YEAR) AS PERSIAN_NEW_YEAR,
TO_NUMBER(PERSIMMON) AS PERSIMMON,
TO_NUMBER(PERU) AS PERU,
TO_NUMBER(PESCATARIAN) AS PESCATARIAN,
TO_NUMBER(PHILIPPINES) AS PHILIPPINES,
TO_NUMBER(PHYLLO_PUFF_PASTRY_DOUGH) AS PHYLLO_PUFF_PASTRY_DOUGH,
TO_NUMBER(PICKLES) AS PICKLES,
TO_NUMBER(PICNIC) AS PICNIC,
TO_NUMBER(PIE) AS PIE,
TO_NUMBER(PINE_NUT) AS PINE_NUT,
TO_NUMBER(PINEAPPLE) AS PINEAPPLE,
TO_NUMBER(PISTACHIO) AS PISTACHIO,
TO_NUMBER(PITTSBURGH) AS PITTSBURGH,
TO_NUMBER(PIZZA) AS PIZZA,
TO_NUMBER(PLANTAIN) AS PLANTAIN,
TO_NUMBER(PLUM) AS PLUM,
TO_NUMBER(POACH) AS POACH,
TO_NUMBER(POBLANO) AS POBLANO,
TO_NUMBER(POKER_GAME_NIGHT) AS POKER_GAME_NIGHT,
TO_NUMBER(POMEGRANATE) AS POMEGRANATE,
TO_NUMBER(POMEGRANATE_JUICE) AS POMEGRANATE_JUICE,
TO_NUMBER(POPPY) AS POPPY,
TO_NUMBER(PORK) AS PORK,
TO_NUMBER(PORK_CHOP) AS PORK_CHOP,
TO_NUMBER(PORK_RIB) AS PORK_RIB,
TO_NUMBER(PORK_TENDERLOIN) AS PORK_TENDERLOIN,
TO_NUMBER(PORT) AS PORT,
TO_NUMBER(PORTLAND) AS PORTLAND,
TO_NUMBER(POT_PIE) AS POT_PIE,
TO_NUMBER(POTATO) AS POTATO,
TO_NUMBER(POTATO_SALAD) AS POTATO_SALAD,
TO_NUMBER(POTLUCK) AS POTLUCK,
TO_NUMBER(POULTRY) AS POULTRY,
TO_NUMBER(POULTRY_SAUSAGE) AS POULTRY_SAUSAGE,
TO_NUMBER(PRESSURE_COOKER) AS PRESSURE_COOKER,
TO_NUMBER(PROSCIUTTO) AS PROSCIUTTO,
TO_NUMBER(PROVIDENCE) AS PROVIDENCE,
TO_NUMBER(PRUNE) AS PRUNE,
TO_NUMBER(PUMPKIN) AS PUMPKIN,
TO_NUMBER(PUNCH) AS PUNCH,
TO_NUMBER(PURIM) AS PURIM,
TO_NUMBER(QUAIL) AS QUAIL,
TO_NUMBER(QUICHE) AS QUICHE,
TO_NUMBER(QUICK__EASY) AS QUICK__EASY,
TO_NUMBER(QUICK_AND_HEALTHY) AS QUICK_AND_HEALTHY,
TO_NUMBER(QUINCE) AS QUINCE,
TO_NUMBER(QUINOA) AS QUINOA,
TO_NUMBER(RABBIT) AS RABBIT,
TO_NUMBER(RACK_OF_LAMB) AS RACK_OF_LAMB,
TO_NUMBER(RADICCHIO) AS RADICCHIO,
TO_NUMBER(RADISH) AS RADISH,
TO_NUMBER(RAISIN) AS RAISIN,
TO_NUMBER(RAMADAN) AS RAMADAN,
TO_NUMBER(RAMEKIN) AS RAMEKIN,
TO_NUMBER(RASPBERRY) AS RASPBERRY,
TO_NUMBER(RAW_) AS RAW_,
TO_NUMBER(RED_WINE) AS RED_WINE,
TO_NUMBER(RHODE_ISLAND) AS RHODE_ISLAND,
TO_NUMBER(RHUBARB) AS RHUBARB,
TO_NUMBER(RICE) AS RICE,
TO_NUMBER(RICOTTA) AS RICOTTA,
TO_NUMBER(ROAST) AS ROAST,
TO_NUMBER(ROOT_VEGETABLE) AS ROOT_VEGETABLE,
TO_NUMBER(ROSEMARY) AS ROSEMARY,
TO_NUMBER(ROSH_HASHANAH_YOM_KIPPUR) AS ROSH_HASHANAH_YOM_KIPPUR,
TO_NUMBER(RUB) AS RUB,
TO_NUMBER(RUM) AS RUM,
TO_NUMBER(RUTABAGA) AS RUTABAGA,
TO_NUMBER(RYE) AS RYE,
TO_NUMBER(SAFFRON) AS SAFFRON,
TO_NUMBER(SAGE) AS SAGE,
TO_NUMBER(SAKE) AS SAKE,
TO_NUMBER(SALAD) AS SALAD,
TO_NUMBER(SALAD_DRESSING) AS SALAD_DRESSING,
TO_NUMBER(SALMON) AS SALMON,
TO_NUMBER(SALSA) AS SALSA,
TO_NUMBER(SAN_FRANCISCO) AS SAN_FRANCISCO,
TO_NUMBER(SANDWICH) AS SANDWICH,
TO_NUMBER(SANDWICH_THEORY) AS SANDWICH_THEORY,
TO_NUMBER(SANGRIA) AS SANGRIA,
TO_NUMBER(SANTA_MONICA) AS SANTA_MONICA,
TO_NUMBER(SARDINE) AS SARDINE,
TO_NUMBER(SAUCE) AS SAUCE,
TO_NUMBER(SAUSAGE) AS SAUSAGE,
TO_NUMBER(SCALLOP) AS SCALLOP,
TO_NUMBER(SCOTCH) AS SCOTCH,
TO_NUMBER(SEAFOOD) AS SEAFOOD,
TO_NUMBER(SEATTLE) AS SEATTLE,
TO_NUMBER(SEED) AS SEED,
TO_NUMBER(SELF_) AS SELF_,
TO_NUMBER(SEMOLINA) AS SEMOLINA,
TO_NUMBER(SESAME) AS SESAME,
TO_NUMBER(SESAME_OIL) AS SESAME_OIL,
TO_NUMBER(SHALLOT) AS SHALLOT,
TO_NUMBER(SHAVUOT) AS SHAVUOT,
TO_NUMBER(SHELLFISH) AS SHELLFISH,
TO_NUMBER(SHERRY) AS SHERRY,
TO_NUMBER(SHOWER) AS SHOWER,
TO_NUMBER(SHRIMP) AS SHRIMP,
TO_NUMBER(SIDE) AS SIDE,
TO_NUMBER(SIMMER) AS SIMMER,
TO_NUMBER(SKEWER) AS SKEWER,
TO_NUMBER(SLOW_COOKER) AS SLOW_COOKER,
TO_NUMBER(SMOKER) AS SMOKER,
TO_NUMBER(SMOOTHIE) AS SMOOTHIE,
TO_NUMBER(SNAPPER) AS SNAPPER,
TO_NUMBER(SORBET) AS SORBET,
TO_NUMBER(SOUFFL_MERINGUE) AS SOUFFL_MERINGUE,
TO_NUMBER(SOUP_STEW) AS SOUP_STEW,
TO_NUMBER(SOUR_CREAM) AS SOUR_CREAM,
TO_NUMBER(SOURDOUGH) AS SOURDOUGH,
TO_NUMBER(SOUTH_CAROLINA) AS SOUTH_CAROLINA,
TO_NUMBER(SOY) AS SOY,
TO_NUMBER(SOY_FREE) AS SOY_FREE,
TO_NUMBER(SOY_SAUCE) AS SOY_SAUCE,
TO_NUMBER(SPAIN) AS SPAIN,
TO_NUMBER(SPARKLING_WINE) AS SPARKLING_WINE,
TO_NUMBER(SPICE) AS SPICE,
TO_NUMBER(SPINACH) AS SPINACH,
TO_NUMBER(SPIRIT) AS SPIRIT,
TO_NUMBER(SPRING) AS SPRING,
TO_NUMBER(SPRITZER) AS SPRITZER,
TO_NUMBER(SQUASH) AS SQUASH,
TO_NUMBER(SQUID) AS SQUID,
TO_NUMBER(ST_LOUIS) AS ST_LOUIS,
TO_NUMBER(ST_PATRICKS_DAY) AS ST_PATRICKS_DAY,
TO_NUMBER(STEAK) AS STEAK,
TO_NUMBER(STEAM) AS STEAM,
TO_NUMBER(STEW) AS STEW,
TO_NUMBER(STIRFRY) AS STIRFRY,
TO_NUMBER(STOCK) AS STOCK,
TO_NUMBER(STRAWBERRY) AS STRAWBERRY,
TO_NUMBER(STUFFING_DRESSING) AS STUFFING_DRESSING,
TO_NUMBER(SUGAR_CONSCIOUS) AS SUGAR_CONSCIOUS,
TO_NUMBER(SUGAR_SNAP_PEA) AS SUGAR_SNAP_PEA,
TO_NUMBER(SUKKOT) AS SUKKOT,
TO_NUMBER(SUMMER) AS SUMMER,
TO_NUMBER(SUPER_BOWL) AS SUPER_BOWL,
TO_NUMBER(SUZANNE_GOIN) AS SUZANNE_GOIN,
TO_NUMBER(SWEET_POTATO_YAM) AS SWEET_POTATO_YAM,
TO_NUMBER(SWISS_CHEESE) AS SWISS_CHEESE,
TO_NUMBER(SWITZERLAND) AS SWITZERLAND,
TO_NUMBER(SWORDFISH) AS SWORDFISH,
TO_NUMBER(TACO) AS TACO,
TO_NUMBER(TAILGATING) AS TAILGATING,
TO_NUMBER(TAMARIND) AS TAMARIND,
TO_NUMBER(TANGERINE) AS TANGERINE,
TO_NUMBER(TAPIOCA) AS TAPIOCA,
TO_NUMBER(TARRAGON) AS TARRAGON,
TO_NUMBER(TART) AS TART,
TO_NUMBER(TEA) AS TEA,
TO_NUMBER(TENNESSEE) AS TENNESSEE,
TO_NUMBER(TEQUILA) AS TEQUILA,
TO_NUMBER(TESTED__IMPROVED) AS TESTED__IMPROVED,
TO_NUMBER(TEXAS) AS TEXAS,
TO_NUMBER(THANKSGIVING) AS THANKSGIVING,
TO_NUMBER(THYME) AS THYME,
TO_NUMBER(TILAPIA) AS TILAPIA,
TO_NUMBER(TOFU) AS TOFU,
TO_NUMBER(TOMATILLO) AS TOMATILLO,
TO_NUMBER(TOMATO) AS TOMATO,
TO_NUMBER(TORTILLAS) AS TORTILLAS,
TO_NUMBER(TREE_NUT) AS TREE_NUT,
TO_NUMBER(TREE_NUT_FREE) AS TREE_NUT_FREE,
TO_NUMBER(TRIPLE_SEC) AS TRIPLE_SEC,
TO_NUMBER(TROPICAL_FRUIT) AS TROPICAL_FRUIT,
TO_NUMBER(TROUT) AS TROUT,
TO_NUMBER(TUNA) AS TUNA,
TO_NUMBER(TURNIP) AS TURNIP,
TO_NUMBER(UTAH) AS UTAH,
TO_NUMBER(VALENTINES_DAY) AS VALENTINES_DAY,
TO_NUMBER(VANILLA) AS VANILLA,
TO_NUMBER(VEAL) AS VEAL,
TO_NUMBER(VEGAN) AS VEGAN,
TO_NUMBER(VEGETABLE) AS VEGETABLE,
TO_NUMBER(VEGETARIAN) AS VEGETARIAN,
TO_NUMBER(VENISON) AS VENISON,
TO_NUMBER(VERMONT) AS VERMONT,
TO_NUMBER(VERMOUTH) AS VERMOUTH,
TO_NUMBER(VINEGAR) AS VINEGAR,
TO_NUMBER(VIRGINIA) AS VIRGINIA,
TO_NUMBER(VODKA) AS VODKA,
TO_NUMBER(WAFFLE) AS WAFFLE,
TO_NUMBER(WALNUT) AS WALNUT,
TO_NUMBER(WASABI) AS WASABI,
TO_NUMBER(WASHINGTON) AS WASHINGTON,
TO_NUMBER(WASHINGTON_DC) AS WASHINGTON_DC,
TO_NUMBER(WATERCRESS) AS WATERCRESS,
TO_NUMBER(WATERMELON) AS WATERMELON,
TO_NUMBER(WEDDING) AS WEDDING ,
TO_NUMBER(WEELICIOUS) AS WEELICIOUS,
TO_NUMBER(WEST_VIRGINIA) AS WEST_VIRGINIA,
TO_NUMBER(WESTWOOD) AS WESTWOOD,
TO_NUMBER(WHEAT_GLUTENFREE) AS WHEAT_GLUTENFREE,
TO_NUMBER(WHISKEY) AS WHISKEY,
TO_NUMBER(WHITE_WINE) AS WHITE_WINE,
TO_NUMBER(WHOLE_WHEAT) AS WHOLE_WHEAT,
TO_NUMBER(WILD_RICE) AS WILD_RICE,
TO_NUMBER(WINDSOR) AS WINDSOR,
TO_NUMBER(WINE) AS WINE,
TO_NUMBER(WINTER) AS WINTER,
TO_NUMBER(WISCONSIN) AS WISCONSIN,
TO_NUMBER(WOK) AS WOK,
TO_NUMBER(YELLOW_SQUASH) AS YELLOW_SQUASH,
TO_NUMBER(YOGURT) AS YOGURT,
TO_NUMBER(YONKERS) AS YONKERS,
TO_NUMBER(YUCA) AS YUCA,
TO_NUMBER(ZUCCHINI) AS ZUCCHINI,
TO_NUMBER(COOKBOOKS) AS COOKBOOKS,
TO_NUMBER(LEFTOVERS) AS LEFTOVERS,
TO_NUMBER(SNACK) AS SNACK,
TO_NUMBER(SNACK_WEEK) AS SNACK_WEEK,
TO_NUMBER(TURKEY) AS TURKEY 
FROM  PANTRYDB.RECIPE_STATS;
